import bcrypt from 'bcryptjs';

const data = {
  users: [
    {
      name: "Pasindu",
      email: "admin@example.com",
      password: bcrypt.hashSync('12345'),
      isAdmin: true
    },
    {
      name: "Umesh",
      email: "user@example.com",
      password: bcrypt.hashSync('12345'),
      isAdmin: false
    }
  ],
  products: [
    {
      // _id: '1',
      name: 'Nike Slim shirt',
      slug: 'nike-slim-shirt',
      category: 'Shirts',
      image: 'https://i.pinimg.com/564x/5d/12/44/5d124468d99c99ce9f85db961477682a.jpg',
      price: 3500,
      countInStock: 1,
      brand: 'Nike',
      rating: 4.5,
      numReviews: 10,
      description: 'Best cotton Shirt',
    },
    {
      // _id: '2',
      name: 'Louis Phillipe Slim shirt',
      slug: 'Louis-Phillipe-slim-shirt',
      category: 'Shirts',
      image: 'https://i.pinimg.com/564x/38/4b/4e/384b4e7a9592fb773fd1fbf748c95322.jpg',
      price: 3500,
      countInStock: 0,
      brand: 'Nike',
      rating: 4.5,
      numReviews: 10,
      description: 'Best cotton Shirt',
    },
    {
      // _id: '3',
      name: 'Arrow Long Sleeve Shirt',
      slug: 'Arrow-Long-Sleeve-Shirt',
      category: 'Shirts',
      image: 'https://i.pinimg.com/564x/1c/ee/b4/1ceeb4c8b89f22f33b3a2c2d4aa81a20.jpg',
      price: 3500,
      countInStock: 1,
      brand: 'Nike',
      rating: 4.5,
      numReviews: 10,
      description: 'Best cotton Shirt',
    },
    {
      // _id: '4',
      name: 'Adidas Slim shirt',
      slug: 'adidas-slim-shirt',
      category: 'Shirts',
      image: 'https://i.pinimg.com/564x/93/0b/b4/930bb4afe1584f6f677a19709a336d57.jpg',
      price: 2500,
      countInStock: 3,
      brand: 'Adidas',
      rating: 2.5,
      numReviews: 5,
      description: 'Best cotton Shirt',
    },
    {
      // _id: '5',
      name: 'Nike Slim Pant',
      slug: 'nike-slim-pant',
      category: 'Pants',
      image: 'https://i.pinimg.com/564x/52/83/d6/5283d6058eaca4a307f79cd87061803c.jpg',
      price: 7500,
      countInStock: 4,
      brand: 'Nike',
      rating: 4.5,
      numReviews: 18,
      description: 'Best cotton Pants',
    },
    {
      // _id: '6',
      name: 'Adidas Slim Pant',
      slug: 'adidas-slim-pant',
      category: 'Pants',
      image: 'https://i.pinimg.com/564x/77/d5/1c/77d51c0d177df22f61c21a0984dcf324.jpg',
      price: 8500,
      countInStock: 4,
      brand: 'Adidas',
      rating: 4.0,
      numReviews: 18,
      description: 'Best cotton Pants',
    },
    {
      // _id: '7',
      name: 'Adidas Fit Suit Trousers',
      slug: 'Adidas-Fit-Suit-Trousers',
      category: 'Pants',
      image: 'https://i.pinimg.com/564x/19/c7/f6/19c7f6d2b71c231a95d81c09b8c19751.jpg',
      price: 8500,
      countInStock: 4,
      brand: 'Adidas',
      rating: 4.0,
      numReviews: 18,
      description: 'Best cotton Pants',
    },
    {
      // _id: '8',
      name: 'Tommy Fit Suit Trousers',
      slug: 'Tommy-Fit-Suit-Trousers',
      category: 'Pants',
      image: 'https://i.pinimg.com/564x/11/23/b5/1123b55cff9baa4ef28a19ff8d4a2b74.jpg',
      price: 9500,
      countInStock: 4,
      brand: 'Adidas',
      rating: 5.0,
      numReviews: 30,
      description: 'Best cotton Pants',
    },
    {
      name: "ANTI-WRINKLE MEN'S LONG SLEEVE SHIRT",
      slug: "ANTI-WRINKLE-MEN'S-LONG-SLEEVE-SHIRT",
      category: 'Shirts',
      image: 'https://i.pinimg.com/564x/86/f6/59/86f6591fafc257eb79207657844116a8.jpg',
      price: 4500,
      countInStock: 6,
      brand: 'Adidas',
      rating: 5.0,
      numReviews: 30,
      description: "Men's Basic Shirt Slim Long Sleeve Square Neck Solid Colored Polyester Black White Light Green 2023 ",
    },
    {
      name: "MEN'S LONG SLEEVE SHIRT BLACK",
      slug: "MEN'S-LONG-SLEEVE-SHIRT_BLACK",
      category: 'Shirts',
      image: 'https://i.pinimg.com/564x/3a/07/09/3a070924d008186276878bc212c353ba.jpg',
      price: 3500,
      countInStock: 10,
      brand: 'TASWT',
      rating: 2.0,
      numReviews: 10,
      description: "Men's Basic Shirt Slim Long Sleeve Square Neck Solid Colored Polyester Black White Light Green 2023 ",
    },
    {
      name: "MEN'S LONG SLEEVE SHIRT WHITE",
      slug: "MEN'S-LONG-SLEEVE-SHIRT_WHITE",
      category: 'Shirts',
      image: 'https://i.pinimg.com/564x/e3/af/51/e3af51106f1406bb2ce68d5f4e4ead37.jpg',
      price: 3500,
      countInStock: 5,
      brand: 'TASWT',
      rating: 3.6,
      numReviews: 16,
      description: "Men's Basic Shirt Slim Long Sleeve Square Neck Solid Colored Polyester Black White Light Green 2023 ",
    },
    {
      name: 'Tommy Fit Suit Trousers Luxury',
      slug: 'Tommy-Fit-Suit-Trousers_Luxury',
      category: 'Pants',
      image: 'https://i.pinimg.com/564x/dc/ba/22/dcba22e7d0f5b5a411eb194162888eff.jpg',
      price: 12500,
      countInStock: 6,
      brand: 'Adidas',
      rating: 5.0,
      numReviews: 30,
      description: 'Best cotton Pants',
    },
  ],
};

export default data;
