const data = {
  products: [
    {
      name: 'Nike Slim shirt',
      slug: 'nike-slim-shirt',
      category: 'Shirts',
      image: 'images/p1.jpg',
      price: 3500,
      countInStock: 1,
      brand: 'Nike',
      rating: 4.5,
      numReviews: 10,
      description: 'Best cotton Shirt',
    },
    {
      name: 'Adidas Slim shirt',
      slug: 'adidas-slim-shirt',
      category: 'Shirts',
      image: 'images/p2.jpg',
      price: 2500,
      countInStock: 3,
      brand: 'Adidas',
      rating: 2.5,
      numReviews: 5,
      description: 'Best cotton Shirt',
    },
    {
      name: 'Nike Slim Pant',
      slug: 'nike-slim-pant',
      category: 'Pants',
      image: 'images/p3.jpg',
      price: 7500,
      countInStock: 4,
      brand: 'Nike',
      rating: 5,
      numReviews: 18,
      description: 'Best cotton Pants',
    },
    {
      name: 'Adidas Slim Pant',
      slug: 'adidas-slim-pant',
      category: 'Pants',
      image: 'images/p4.jpg',
      price: 8500,
      countInStock: 4,
      brand: 'Adidas',
      rating: 5,
      numReviews: 18,
      description: 'Best cotton Pants',
    },
  ],
};

export default data;
